### PR TITLE
Pubsub listen/unlisten multi channel support

### PR DESCRIPTION
**Pull request by mikemagowan**
- Support multiple channels in listen/unlisten which map to a single SUBSCRIBE and/or PSUBSCRIBE redis call
  - Improvements to glob pattern matching beyond the current wildcard (*) only matching for PSUBSCRIBE
  - Minor pubsub documentation fixes

### CODE REVIEW

**Comment by jhthorsen** [comment]
Thanks for the PR, but I’m pretty sure I’m going to close it. The reason is that there’s too many things going on. Can you open multiple smaller PRs?

Before you go trough the effort, I would like to know the usecase for multiple channels in listen/unlisten. It seems like a lot of code inside Mojo::Redis, instead of just looping over whatever from the outside. Another thing to take into consideration is that it will divert Mojo::Redis from other modules such as Mojo::Pg.

**Comment by mikemagowan** [comment]
We have some legacy code that's still using Mojo::Redis2.  In the analysis of the work to be done to refactor this to support Mojo::Redis we realised that we have websocket code that subscribes to a fair amount of pubsub channels (it's a bit of a hierarchy based on geographical location amongst other things).  In most cases I think we're looking at around 6 or 7 channels and at worst around 20 to 30.

In addition the client end of the websocket is running across a mobile data connection which can best be described as 'poor'.  This means that the websockets drop and reconnect frequently.  Consequently the subscribe calls are essentially a continuous stream and a web service restart is a veritable redis subscription storm.

To move to Mojo::Redis would amplify the number of subscribe calls and isn't ideal.

When creating the PR I did spot the reference to Mojo::Pg but noted that there were already divergences in the code (e.g. Mojo::Pg has reset which Mojo::Redis doesn't and Mojo::Redis has the keyspace calls and patterned subscriptions which Mojo::Pg doesn't have).  In addition a call to listen with a single channel still works as expected with no change required to any code.  This is a fully backward compatible change.

I'm not sure if it's possible to simplify it any more than it currently is except to perhaps split up the code/test and documentary changes into separate PRs?

No problem with closing if you don't want to accept - it won't be wasted work as I'll just use the fork internally until we can perhaps look to refactor the entire app.

**Comment by jhthorsen** [comment]
@mikemagowan: I'm guessing you have moved on, but if you're still interested, I would not mind adding you as a maintainer, and you can make smaller changes directly in the main branch.

**Comment by mikemagowan** [comment]
@jhthorsen yeah that's no problem - happy to be added 👍

**Comment by jhthorsen** [comment]
Cool! Take it away, but please perltidy the changes 👍

**Pull request closed without merging**
