### PR TITLE
Weaken circular reference in redis response parser

### LINKED ISSUE #52: Memory leak
Hello!
I have a very simple test script that consumes too much memory over time.

```perl
use Mojo::Redis;
$|=1;

my $redis = Mojo::Redis->new( 'redis://localhost:6379' );

sub process_event {
    my $ev = $redis->db->exists( "non_existent_key" );
    print ".";
}

my $i = 0;
while ( 1 ) {
    process_event;
    $i++;
    if ( $i % 1000 == 0 ) {
        print "\n", $i, "\n";
    }
}
```

After about 300000 iterations memory consumption grows from 35 to 350Mb.

(Out of interest I tried to replace Mojo::Redis with other perl redis modules (like Mojo::Redis2 and Redis). Mojo::Redis2 also leaks but to a lesser extent. And with Redis memory consumption stayed the same for almost 500000 iterations, so it obviously doesn't leak.)

### PR DESCRIPTION
**Pull request by Grinnz**
Alternative to #58 in order to resolve #52.

### CODE REVIEW

**Comment by TFBW** [comment]
I have applied this patch locally and performed a test with Devel::MAT.

- My code runs and serves no requests, then dumps memory (baseline): Heap contains 83010 objects
- My code runs and serves 500 requests, then dumps memory, **no weaken**: Heap contains 429484 objects
- My code runs and serves 500 requests, then dumps memory, **with weaken**: Heap contains 83048 objects

The net difference of 38 between baseline and with-weaken is not suspicious.

**Comment by jhthorsen** [comment]
I'm ok with using current_sub instead. What do you think?

**Comment by jhthorsen** [comment]
I'm fine with either of the solutions, though I would prefer the `__SUB__` version, since I think it's a lot easier to read.

@Grinnz: I added you as comaint now, so you are free to merge and make a new release. I can also make a release after this is fixed, if you prefer.

**Comment by jhthorsen** [comment]
Picked #60 instead.

**Pull request closed without merging**
