### PR TITLE
Support Redis 6 AUTH with optional username

### PR DESCRIPTION
**Pull request by Jayceh**
This should allow existing < 6 behavior to continue, and the v6 ACL access to coexist.

### CODE REVIEW

**Comment by Grinnz** [comment]
This looks like a good idea. Should be documented and tested, to the extent it can be without necessarily having a redis 6 server.

**Comment by Grinnz** [comment]
My one concern is that the placeholder 'x' for username has been common in the past which would now result in sending an invalid auth command on redis < 6. Maybe it needs to be an option.

**Comment by Jayceh** [comment]
yeah, in v6, you can continue to pass *no* username and the password will work against the default user if configured, but otherwise takes the new behavior. Not sure how to well-test it without standing up the actual server. I locally used it against a docker image on both versions, but that was just to get it working.

**Comment by Grinnz** [comment]
My point is that common practice is to set userinfo in the URL you would pass, which requires both a username and password, so something like 'x:password' would be commonly seen in code in the wild using Mojo::Redis currently. So it would not be a good idea to make that suddenly start doing something different.

**Comment by Jayceh** [comment]
So how common do you think the literal 'x' is? worth writing special handling? or a documented change path? Any handling you would prefer to see?

**Comment by Grinnz** [comment]
I can't say how common it is. My preference would be that using the username portion of userinfo be opt-in. It could be possible to deprecate passing a username with a length when that opt in is not taken, and eventually make this default behavior.

**Comment by jhthorsen** [comment]
@Jayceh: What is the status of this PR? Should I close it, or will you address the requested changes?

**Comment by jhthorsen** [comment]
I think this PR has gone stale 😞

**Pull request closed without merging**
